name: reddist_clone_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons:
  firebase_core: 
  firebase_storage: 
  cloud_firestore: 
  gap:
  firebase_auth: 
  google_sign_in:
  flutter_riverpod:
  fpdart: 
  routemaster:
  dotted_border: 
  file_picker: 
  shared_preferences:
  uuid: 
  any_link_preview:     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/loginEmote.png
    - assets/images/logo.png
    - assets/images/awards/
