// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB98B-aBkyFCiph0za2KUUkTGKdtnnSweg',
    appId: '1:643454300941:web:86319f7813f18bb837f644',
    messagingSenderId: '643454300941',
    projectId: 'reddistapp',
    authDomain: 'reddistapp.firebaseapp.com',
    storageBucket: 'reddistapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGyJ-C50sQ6xOvfAYOF5FRLxVlSwnVuaA',
    appId: '1:643454300941:android:316ca42ead1ce42937f644',
    messagingSenderId: '643454300941',
    projectId: 'reddistapp',
    storageBucket: 'reddistapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFLTF3oBhD9PrNAWDbbyUc1egj4Av5ucQ',
    appId: '1:643454300941:ios:b59d891814b774dd37f644',
    messagingSenderId: '643454300941',
    projectId: 'reddistapp',
    storageBucket: 'reddistapp.appspot.com',
    iosBundleId: 'com.example.reddistCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFLTF3oBhD9PrNAWDbbyUc1egj4Av5ucQ',
    appId: '1:643454300941:ios:f0b1d9d967d9f23737f644',
    messagingSenderId: '643454300941',
    projectId: 'reddistapp',
    storageBucket: 'reddistapp.appspot.com',
    iosBundleId: 'com.example.reddistCloneApp.RunnerTests',
  );
}
